baseURL = "https://lithespan.com/"
locale = "en-US"
title = "Lithespan"
copyright = "Copyright 2026 Lithespan"
cleanDestinationDir = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  description = "Lithespan builds and maintains software for defined hardware, operating systems, and workloads, from languages and compilers to runtimes, systems software, packages, and images."
  email = "contact@lithespan.com"
  github = "https://github.com/lithespan"
  ogImage = "/og.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[minify]
  minifyOutput = true
